name: Generate ASCII Artwork

on: push

jobs:
  ascii_job:
    runs-on: ubuntu-latest
    steps:
    - name: checkout Repo
      uses: actions/checkout@v4

    - name: checkout Repo Files
      run: |
        cd .github/workflows/
        ls -ltra

    - name: Executing Shell Script
      run: |
        sudo chmod +x ascii.sh
        ./ascii.sh
      
   
      
