name : my workflow

on: push
jobs:
    first_job:
        runs-on: ubuntu-latest
        steps: 
        - name: checkout Repository
          uses: actions/checkout@v4

        - name: welcome message
          run: echo "this is my first job"

        - name: list file
          run: ls

        - name: read message
          run: cat README.md
